apiVersion: v1
kind: Service
metadata:
  name: guestbook-app-service
  labels:
    name: guestbook-app-service
spec:
  type: LoadBalancer
  selector:
    name: guestbook-app
    tier: frontend
  ports:
  - port: 80
    targetPort: 80