apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-app-deployment
  labels:
    name: guestbook-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: guestbook-app
      tier: frontend
  template:
    metadata:
      name: guestbook-app
      labels:
        name: guestbook-app
        tier: frontend
    spec:
      containers:
      - name: guestbook-app
        image: gcr.io/google-samples/gb-frontend:v4
        ports:
        - containerPort: 80