apiVersion: v1
kind: Service
metadata:
  name: redis-master-service
  labels:
    name: redis-master-service
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-master
    tier: backend
