apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave-deployment
  labels:
    name: redis-slave-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: redis-slave
      tier: backend
  template:
    metadata:
      name: redis-slave
      labels:
        name: redis-slave
        tier: backend
    spec:
      containers:
      - name: redis-slave
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        env:
        - name: GET_HOSTS_FROM
          value: dns